-- ============================================================================
-- Credit notes issued against invoices. Reduce GST output liability; each is a
-- separate document with its own number, referencing the original invoice.
-- Only the admin can issue/edit; all allow-listed users can read (for the GST
-- export). Run once in the Supabase SQL Editor.
-- ============================================================================
create table if not exists public.credit_notes (
  id                 bigint generated by default as identity primary key,
  invoice_id         bigint,        -- original billable_items.id
  invoice_number     text,          -- snapshot of the original invoice number
  credit_note_number text,
  cn_date            date,
  amount             numeric not null default 0,  -- taxable value credited
  reason             text,
  created_by         text,
  created_at         timestamptz default now()
);
create index if not exists credit_notes_invoice_id_idx on public.credit_notes (invoice_id);

alter table public.credit_notes enable row level security;

drop policy if exists cn_read on public.credit_notes;
create policy cn_read on public.credit_notes for select to authenticated
  using (public.is_allowed_user());

drop policy if exists cn_write on public.credit_notes;
create policy cn_write on public.credit_notes for all to authenticated
  using (public.is_app_admin()) with check (public.is_app_admin());

grant all on table public.credit_notes to authenticated;
grant usage, select on all sequences in schema public to authenticated;
