-- ============================================================================
-- Employees table for the Disbursement (salary) module. Holds sensitive data
-- (salary + bank account), so it's locked to the same allow-list as everything
-- else via RLS. Run once in the Supabase SQL Editor.
-- ============================================================================
create table if not exists public.employees (
  id               bigint generated by default as identity primary key,
  name             text not null,
  salary           numeric not null default 0,
  ifsc             text,
  account_number   text,
  is_active        boolean default true,
  created_by_email text,
  created_at       timestamptz default now()
);

alter table public.employees enable row level security;
drop policy if exists allowlist_all on public.employees;
create policy allowlist_all on public.employees for all to authenticated
  using (public.is_allowed_user()) with check (public.is_allowed_user());
grant all on table public.employees to authenticated;
grant usage, select on all sequences in schema public to authenticated;
